---
- name: Creating user using ansible
  hosts: 10.0.0.164
  become: yes
  vars_files:
    - "/home/ansible/user_vars.yml"
  tasks:
    - name: Adding user to a system
      user: 
        name: "{{ item }}"
        append: yes
        groups: wheel
        generate_ssh_key: yes
        home: "/home/{{ item }}"
        password: "{{ user_password }}" 
        shell: "{{ user_shell }}"
      loop: "{{ create_users }}"
 