---
- name: Add config file to a server
  become: yes
  hosts: 10.0.0.152
  roles:
    - /home/ansible/oleg.nagios_add_servers
- name: Configure nagios client
  hosts: 10.0.0.164
  become: yes
  roles:
    - /home/ansible/oleg.nagios-client